HyperGraph:
    model: HyperGraph
    dataset_id: taobao_x1_sub_seq_only_user
    loss: 'binary_crossentropy'
    metrics: ['logloss', 'AUC']
    task: binary_classification
    optimizer: adam
    learning_rate: 1.e-3
    embedding_regularizer: 0
    net_regularizer: 0
    batch_size: 4096
    embedding_dim: 10
    graph_layer: 2
    batch_norm: False
    epochs: 20
    bpr_batch_size: 8096
    shuffle: True
    seed: 2022
    monitor: 'AUC'
    monitor_mode: 'max'
    weight_decay: 1.0e-4


HyperGraphCustom:
    model: HyperGraphCustom
    dataset_id: taobao_x1_sub_seq_only_user
    loss: 'binary_crossentropy'
    metrics: ['logloss', 'AUC']
    task: binary_classification
    optimizer: adam
    learning_rate: 1.e-3
    embedding_regularizer: 0
    net_regularizer: 0
    batch_size: 4096
    embedding_dim: 10
    graph_layer: 2
    batch_norm: False
    epochs: 20
    bpr_batch_size: 8096
    shuffle: True
    seed: 2022
    monitor: 'AUC'
    monitor_mode: 'max'
    weight_decay: 1.0e-4

HyperGraphCustomBipartite:
    model: HyperGraphCustomBipartite
    dataset_id: taobao_x1_sub_seq_only_user
    loss: 'binary_crossentropy'
    metrics: ['logloss', 'AUC']
    task: binary_classification
    optimizer: adam
    learning_rate: 1.e-3
    embedding_regularizer: 0
    net_regularizer: 0
    batch_size: 4096
    embedding_dim: 10
    graph_layer: 2
    batch_norm: False
    epochs: 20
    bpr_batch_size: 8096
    shuffle: True
    seed: 2022
    monitor: 'AUC'
    monitor_mode: 'max'
    weight_decay: 1.0e-4

HyperGraphCustomBipartiteDisen:
    model: HyperGraphCustomBipartiteDisen
    dataset_id: taobao_x1_sub_seq_only_user
    loss: 'binary_crossentropy'
    metrics: ['logloss', 'AUC']
    task: binary_classification
    optimizer: adam
    learning_rate: 1.e-3
    embedding_regularizer: 0
    net_regularizer: 0
    batch_size: 4096
    embedding_dim: 10
    graph_layer: 1
    batch_norm: False
    epochs: 20
    bpr_batch_size: 8096
    shuffle: True
    seed: 2022
    monitor: 'AUC'
    monitor_mode: 'max'
    weight_decay: 1.0e-4

HyperGraphCustomBipartiteDisenGAT:
    model: HyperGraphCustomBipartiteDisenGAT
    dataset_id: taobao_x1_sub_seq_only_user
    loss: 'binary_crossentropy'
    metrics: ['logloss', 'AUC']
    task: binary_classification
    optimizer: adam
    learning_rate: 1.e-3
    embedding_regularizer: 0
    net_regularizer: 0
    batch_size: 4096
    embedding_dim: 10
    graph_layer: 1
    batch_norm: False
    epochs: 20
    bpr_batch_size: 8096
    shuffle: True
    seed: 2022
    monitor: 'AUC'
    monitor_mode: 'max'
    weight_decay: 1.0e-4


HyperGraphCustomBipartiteDisenGATCL:
    model: HyperGraphCustomBipartiteDisenGATCL
    dataset_id: taobao_x1_sub_seq_only_user
    loss: 'binary_crossentropy'
    metrics: ['logloss', 'AUC']
    task: binary_classification
    optimizer: adam
    learning_rate: 1.e-3
    embedding_regularizer: 0
    net_regularizer: 0
    batch_size: 4096
    embedding_dim: 10
    graph_layer: 1
    batch_norm: False
    epochs: 20
    bpr_batch_size: 8096
    shuffle: True
    seed: 2022
    monitor: 'AUC'
    monitor_mode: 'max'
    weight_decay: 1.0e-4


HyperGraphCustomBipartiteDisenGATCLUser:
    model: HyperGraphCustomBipartiteDisenGATCLUser
    dataset_id: taobao_x1_sub_seq_only_user
    loss: 'binary_crossentropy'
    metrics: ['logloss', 'AUC']
    task: binary_classification
    optimizer: adam
    learning_rate: 1.e-3
    embedding_regularizer: 0
    net_regularizer: 0
    batch_size: 4096
    embedding_dim: 10
    graph_layer: 1
    batch_norm: False
    epochs: 50
    bpr_batch_size: 8096
    shuffle: True
    seed: 2022
    monitor: 'AUC'
    monitor_mode: 'max'
    weight_decay: 1.0e-4


HyperGraphCustomBipartiteDisenGATCLUserV2:
    model: HyperGraphCustomBipartiteDisenGATCLUserV2
    dataset_id: taobao_x1_sub_seq_only_user
    loss: 'binary_crossentropy'
    metrics: ['logloss', 'AUC']
    task: binary_classification
    optimizer: adam
    learning_rate: 1.e-3
    embedding_regularizer: 0
    net_regularizer: 0
    batch_size: 4096
    embedding_dim: 10
    graph_layer: 2
    batch_norm: False
    epochs: 10
    bpr_batch_size: 8096
    shuffle: True
    seed: 2022
    monitor: 'AUC'
    monitor_mode: 'max'
    weight_decay: 1.0e-4
    iterations: 3
    add_norm: True
    encoder_model: 'lightgcn'
    # encoder_model: 'disengcn'
    # encoder_model: 'embedding'
    channels: 2

HyperGraphCustomBipartiteDisenGATVAE:
    model: HyperGraphCustomBipartiteDisenGATVAE
    dataset_id: taobao_x1_sub_seq_only_user
    loss: 'binary_crossentropy'
    metrics: ['logloss', 'AUC']
    task: binary_classification
    optimizer: adam
    learning_rate: 1.e-3
    embedding_regularizer: 0
    net_regularizer: 0
    batch_size: 4096
    embedding_dim: 10
    graph_layer: 2
    batch_norm: False
    epochs: 20
    bpr_batch_size: 8096
    shuffle: True
    seed: 2022
    monitor: 'AUC'
    monitor_mode: 'max'
    weight_decay: 1.0e-4
    iterations: 3
    add_norm: False
    channels: 2

HyperGraphCustomBipartiteDisenGATVAEV3:
    model: HyperGraphCustomBipartiteDisenGATVAEV3
    dataset_id: taobao_x1_sub_seq_only_user
    loss: 'binary_crossentropy'
    metrics: ['logloss', 'AUC']
    task: binary_classification
    optimizer: adam
    learning_rate: 1.e-3
    embedding_regularizer: 0
    net_regularizer: 0
    batch_size: 4096
    # embedding_dim: 64
    embedding_dim: 10
    graph_layer: 2
    batch_norm: False
    epochs: 10
    bpr_batch_size: 8096
    shuffle: True
    seed: 2022
    monitor: 'AUC'
    monitor_mode: 'max'
    weight_decay: 1.0e-4
    iterations: 3
    add_norm: True
    # encoder_model: 'disengcn'
    encoder_model: 'lightgcn'
    channels: 2


HyperGraphCustomBipartiteDisenGATVAEV4:
    model: HyperGraphCustomBipartiteDisenGATVAEV4
    dataset_id: taobao_x1_sub_seq_only_user
    loss: 'binary_crossentropy'
    metrics: ['logloss', 'AUC']
    task: binary_classification
    optimizer: adam
    learning_rate: 1.e-3
    embedding_regularizer: 0
    net_regularizer: 0
    batch_size: 4096
    embedding_dim: 10
    graph_layer: 2
    batch_norm: False
    epochs: 0
    bpr_batch_size: 8096
    shuffle: True
    seed: 2022
    monitor: 'AUC'
    monitor_mode: 'max'
    weight_decay: 1.0e-4
    iterations: 3
    add_norm: True
    encoder_model: 'disengcn'
    channels: 2
