DESTINE_base:
    model: DESTINE
    dataset_id: TBD
    loss: 'binary_crossentropy'
    metrics: ['logloss', 'AUC']
    task: binary_classification
    optimizer: adam
    learning_rate: 1.e-3
    embedding_regularizer: 0
    net_regularizer: 0
    batch_size: 4096
    embedding_dim: 40
    attention_dim: 40
    num_heads: 2
    attention_layers: 2
    dnn_hidden_units: [400, 400, 400]
    dnn_activations: relu
    att_dropout: 0
    net_dropout: 0
    relu_before_att: False
    use_scale: True
    use_wide: False
    residual_mode: "each_layer"
    batch_norm: True
    epochs: 100
    shuffle: True
    seed: 2021
    monitor: 'AUC'
    monitor_mode: 'max'
