EDCN_base:
    model: EDCN
    dataset_id: TBD
    loss: 'binary_crossentropy'
    metrics: ['logloss', 'AUC']
    task: binary_classification
    optimizer: adam
    learning_rate: 1.e-3
    embedding_regularizer: 0
    net_regularizer: 0
    batch_size: 4096
    embedding_dim: 40
    num_cross_layers: 3
    hidden_activations: ReLU
    bridge_type: "hadamard_product"
    use_regulation_module: False
    temperature: 1
    batch_norm: False
    net_dropout: 0
    epochs: 100
    shuffle: True
    seed: 2022
    monitor: 'AUC'
    monitor_mode: 'max'
